name: Documentation

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs
          pip install -r requirements.txt
          cd ..
          pip install .

      - name: Build Documentation
        run: |
          cd docs
          make html
          # Create .nojekyll file to allow _* files
          touch build/html/.nojekyll

      - name: Prepare deployment directory
        run: |
          cd docs/build/html
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            mkdir -p dev
            cp -r assets dev/
            cp -r _sources dev/
            cp -r _static dev/
            cp -r api dev/
            cp -r tutorials dev/
            cp -r *.html dev/
            cp -r .nojekyll dev/
            cp -r *.js* dev/
          else
            mkdir -p stable
            cp -r assets stable/
            cp -r _sources stable/
            cp -r _static stable/
            cp -r api stable/
            cp -r tutorials stable/
            cp -r *.html stable/
            cp -r .nojekyll stable/
            cp -r *.js* stable/
          fi
          # Create redirect index
          echo '<meta http-equiv="refresh" content="0; url=./dev/">' > index.html

      - name: Deploy Documentation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/build/html
          target-folder: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'stable' }}
          clean: true