name: Documentation

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs
          pip install -r requirements.txt
          cd ..
          pip install .

      - name: Build Documentation
        run: |
          cd docs
          make html
          touch build/html/.nojekyll

      - name: Prepare deployment directory
        run: |
          cd docs
          mkdir -p deploy
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            mkdir -p deploy/dev
            cp -r build/html/* deploy/dev/
            echo '<meta http-equiv="refresh" content="0; url=./dev/">' > deploy/index.html
          else
            mkdir -p deploy/stable
            cp -r build/html/* deploy/stable/
            echo '<meta http-equiv="refresh" content="0; url=./stable/">' > deploy/index.html
          fi
          cp build/html/.nojekyll deploy/

      - name: Deploy Documentation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/deploy
          clean: true