name: Documentation

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs
          pip install -r requirements.txt
          pip install sphinx-rtd-theme --upgrade
          cd ..
          pip install .

      - name: Build Documentation
        run: |
          cd docs
          # Set the correct base URL depending on the branch
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            make html SPHINXOPTS="-D html_baseurl=https://david-araripe.github.io/UniProtMapper/dev/"
          else
            make html SPHINXOPTS="-D html_baseurl=https://david-araripe.github.io/UniProtMapper/stable/"
          fi
          touch build/html/.nojekyll

      - name: Deploy Documentation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/build/html
          target-folder: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'stable' }}
          clean: true