name: Documentation

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd docs
          pip install -r requirements.txt
          pip install sphinx-rtd-theme --upgrade
          cd ..
          pip install .

      - name: Build Documentation
        run: |
          cd docs
          make html

      - name: Create root .nojekyll # Should be at the root, so we create sub-dir & push it
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        run: |
          mkdir -p gh-pages-root
          touch gh-pages-root/.nojekyll

      - name: Deploy .nojekyll
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages-root
          clean: false

      - name: Deploy Documentation
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/html
          target-folder: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'stable' }}
          clean: false